/**
 * MDX content access layer.
 * Uses a pre-built JSON manifest (generated by scripts/prebuild-content.mjs)
 * so it works on Edge runtimes (Cloudflare Workers) without Node.js fs.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
import manifest from './content-manifest.json';

export type ContentMeta = {
  slug: string;
  title: string;
  description: string;
  order?: number;
  next?: string;
  category?: string;
  related?: string[];
};

export type ContentItem = {
  meta: ContentMeta;
  content: string;
};

export type TocItem = {
  id: string;
  text: string;
  level: number;
};

type ManifestEntry = {
  meta: ContentMeta;
  content: string;
};

type ManifestType = Record<string, Record<string, ManifestEntry>>;
type Manifest = Record<string, ManifestType>;

const data = manifest as unknown as Manifest;

export function getContentItem(
  type: 'course' | 'glossary',
  locale: string,
  slug: string
): ContentItem | null {
  // Try requested locale first, then fallback to English
  const entry =
    data[type]?.[locale]?.[slug] ?? data[type]?.['en']?.[slug] ?? null;

  if (!entry) return null;

  return {
    meta: entry.meta,
    content: entry.content,
  };
}

export function getAllSlugs(
  type: 'course' | 'glossary',
  locale: string
): string[] {
  const localeData = data[type]?.[locale];
  if (!localeData) return [];
  return Object.keys(localeData);
}

export function getAllContentMeta(
  type: 'course' | 'glossary',
  locale: string
): ContentMeta[] {
  const localeData = data[type]?.[locale];
  if (!localeData) return [];

  const items = Object.values(localeData).map((entry) => entry.meta);

  // Sort by order for courses, alphabetically for glossary
  if (type === 'course') {
    items.sort((a, b) => (a.order ?? 99) - (b.order ?? 99));
  } else {
    items.sort((a, b) => a.title.localeCompare(b.title));
  }

  return items;
}

export function extractToc(content: string): TocItem[] {
  const headingRegex = /^(#{2,3})\s+(.+)$/gm;
  const toc: TocItem[] = [];
  let match;

  while ((match = headingRegex.exec(content)) !== null) {
    const level = match[1].length;
    const text = match[2].trim();
    const id = text
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fff]+/gi, '-')
      .replace(/^-|-$/g, '');
    toc.push({ id, text, level });
  }

  return toc;
}
